#!/usr/bin/env python3
"""
Ennoia License Generator
Run this tool to generate license files for customers.

Usage:
    python generate_license.py --customer "Company Name" --email "user@example.com" \
        --machine-id "abc123..." --tinysa-serial "TSA-12345" --days 365

Requirements:
    - private_key.pem must exist (generated by generate_keys.py)
    - Run this on Ennoia admin machine only
"""

import argparse
import json
import base64
import os
from datetime import datetime, timedelta
from cryptography.hazmat.primitives import hashes, serialization
from cryptography.hazmat.primitives.asymmetric import padding
from cryptography.hazmat.backends import default_backend


def load_private_key(path="private_key.pem"):
    """Load the private key from file."""
    with open(path, "rb") as f:
        return serialization.load_pem_private_key(
            f.read(),
            password=None,
            backend=default_backend()
        )


def sign_license(license_data: dict, private_key) -> str:
    """Sign the license data and return base64-encoded signature."""
    payload = json.dumps(license_data, sort_keys=True).encode()
    signature = private_key.sign(
        payload,
        padding.PSS(
            mgf=padding.MGF1(hashes.SHA256()),
            salt_length=padding.PSS.MAX_LENGTH
        ),
        hashes.SHA256()
    )
    return base64.b64encode(signature).decode()


def generate_license(
    customer: str,
    email: str,
    machine_id: str,
    tinysa_serial: str,
    days: int = 365,
    tier: str = "standard",
    private_key_path: str = "private_key.pem"
) -> dict:
    """
    Generate a signed license file.

    Args:
        customer: Customer/company name
        email: Customer email
        machine_id: Machine fingerprint (from get_machine_id())
        tinysa_serial: tinySA device serial (from get_tinysa_serial())
        days: License validity in days (60, 365, etc.)
        tier: License tier (trial, standard, professional, perpetual)
        private_key_path: Path to private key file

    Returns:
        dict: Complete license file with signature
    """
    # Load private key
    private_key = load_private_key(private_key_path)

    # Calculate expiration
    if tier == "perpetual":
        expires = "2099-12-31"
    else:
        expires = (datetime.now() + timedelta(days=days)).strftime("%Y-%m-%d")

    # Build license data
    license_data = {
        "customer": customer,
        "email": email,
        "machine_id": machine_id,
        "tinysa_serial": tinysa_serial,
        "tier": tier,
        "issued": datetime.now().strftime("%Y-%m-%d"),
        "expires": expires,
        "features": get_features_for_tier(tier)
    }

    # Sign the license
    signature = sign_license(license_data, private_key)

    return {
        "license": license_data,
        "signature": signature
    }


def get_features_for_tier(tier: str) -> list:
    """Get features list based on license tier."""
    features = {
        "trial": ["basic_scan", "spectrum_view"],
        "standard": ["basic_scan", "spectrum_view", "wifi_scan", "csv_export"],
        "professional": ["basic_scan", "spectrum_view", "wifi_scan", "csv_export",
                         "cellular_id", "advanced_analysis", "slm_mode"],
        "perpetual": ["all"]
    }
    return features.get(tier, features["standard"])


def main():
    parser = argparse.ArgumentParser(
        description="Generate Ennoia license files",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate 60-day trial license
  python generate_license.py --customer "Test User" --email "test@example.com" \\
      --machine-id "abc123" --tinysa-serial "TSA001" --days 60 --tier trial

  # Generate 1-year standard license
  python generate_license.py --customer "Acme Corp" --email "user@acme.com" \\
      --machine-id "def456" --tinysa-serial "TSA002" --days 365 --tier standard

  # Generate perpetual professional license
  python generate_license.py --customer "Enterprise Inc" --email "admin@enterprise.com" \\
      --machine-id "ghi789" --tinysa-serial "TSA003" --tier perpetual

To get machine-id and tinysa-serial, run on customer's machine:
  python ennoia_core.py
        """
    )

    parser.add_argument("--customer", required=True, help="Customer/company name")
    parser.add_argument("--email", required=True, help="Customer email")
    parser.add_argument("--machine-id", required=True, help="Machine fingerprint")
    parser.add_argument("--tinysa-serial", required=True, help="tinySA device serial")
    parser.add_argument("--days", type=int, default=365, help="Validity in days (default: 365)")
    parser.add_argument("--tier", choices=["trial", "standard", "professional", "perpetual"],
                        default="standard", help="License tier (default: standard)")
    parser.add_argument("--output", "-o", default="license.json",
                        help="Output file path (default: license.json)")
    parser.add_argument("--private-key", default="private_key.pem",
                        help="Path to private key (default: private_key.pem)")

    args = parser.parse_args()

    # Check private key exists
    if not os.path.isfile(args.private_key):
        print(f"Error: Private key not found at {args.private_key}")
        print("Run generate_keys.py first to create the key pair.")
        return 1

    # Generate license
    print(f"Generating license for {args.customer}...")
    license_file = generate_license(
        customer=args.customer,
        email=args.email,
        machine_id=args.machine_id,
        tinysa_serial=args.tinysa_serial,
        days=args.days,
        tier=args.tier,
        private_key_path=args.private_key
    )

    # Save to file
    with open(args.output, "w") as f:
        json.dump(license_file, f, indent=2)

    print(f"\nLicense generated successfully!")
    print(f"Output: {args.output}")
    print(f"\nLicense Details:")
    print(f"  Customer:    {license_file['license']['customer']}")
    print(f"  Email:       {license_file['license']['email']}")
    print(f"  Machine ID:  {license_file['license']['machine_id']}")
    print(f"  Device:      {license_file['license']['tinysa_serial']}")
    print(f"  Tier:        {license_file['license']['tier']}")
    print(f"  Issued:      {license_file['license']['issued']}")
    print(f"  Expires:     {license_file['license']['expires']}")
    print(f"  Features:    {', '.join(license_file['license']['features'])}")
    print(f"\nSend {args.output} to the customer.")

    return 0


if __name__ == "__main__":
    exit(main())
